#!/bin/bash
# Auto-generated by MCL_AutoRefresh_Install.command — do not edit manually
source "/Users/luciakamau/.mcl_creds" 2>/dev/null
export SQL_SERVER="173.249.59.109"
export SQL_PORT="1433"
export SQL_DATABASE="mwananchidy365"
export SQL_USER="monday"
export SQL_PASSWORD

REPO="/Users/luciakamau/mwananchi-portfolio"
VENV_PY="/Users/luciakamau/mwananchi-portfolio/.venv/bin/python3"
SCRIPT="/Users/luciakamau/mwananchi-portfolio/mcl_refresh.py"
TODAY=$(date +"%Y-%m-%d")

# Run daily snapshot (dated filename)
"$VENV_PY" "$SCRIPT" "$TODAY" "ALL" >> "/Users/luciakamau/.mcl_refresh.log" 2>&1

# macOS notification
osascript -e "display notification \"Daily snapshot ready: MCL_Portfolio_${TODAY}.xlsx\" with title \"Mwananchi Credit\" sound name \"Glass\""
