#!/bin/bash
# Mwananchi Credit — Auto-Refresh Installer
# Sets up two background tasks:
#   1. Refresh Excel every 5 minutes  (MCL_Portfolio_LIVE.xlsx)
#   2. Daily snapshot at 5:00 PM      (MCL_Portfolio_YYYY-MM-DD.xlsx)
# Double-click this file to install (right-click > Open on first run)

REPO_DIR="$HOME/mwananchi-portfolio"
VENV="$REPO_DIR/.venv"
SCRIPT="$REPO_DIR/mcl_refresh.py"
CREDS="$HOME/.mcl_creds"
WRAPPER="$REPO_DIR/mcl_background_refresh.sh"
AGENTS_DIR="$HOME/Library/LaunchAgents"
LIVE_PLIST="$AGENTS_DIR/com.mcl.portfolio.refresh.plist"
DAILY_PLIST="$AGENTS_DIR/com.mcl.portfolio.daily.plist"
LOG="$HOME/.mcl_refresh.log"

step() { echo ""; echo "[ $1 ] $2"; }
ok()   { echo "       OK: $*"; }
fail() { echo ""; echo "  FAILED: $*"; echo ""; read -p "Press Enter to close..."; exit 1; }

clear
echo ""
echo "========================================================"
echo "  Mwananchi Credit Ltd"
echo "  Auto-Refresh Installer"
echo "========================================================"
echo ""
echo "  This will set up:"
echo "    - Excel refresh every 5 minutes (background, always on)"
echo "    - Daily 5:00 PM snapshot saved with today's date"
echo ""
read -p "  Press Enter to continue or Ctrl+C to cancel..."

# ── STEP 1: Check repo ──────────────────────────────────────
step 1 "Checking repository..."
[ -d "$REPO_DIR/.git" ] || fail "Repo not found at $REPO_DIR. Run MCL_Excel_Refresh.command first."
[ -f "$SCRIPT" ]        || fail "mcl_refresh.py not found in repo. Run MCL_Excel_Refresh.command first."
ok "Repo found"

# ── STEP 2: Check venv ──────────────────────────────────────
step 2 "Checking Python environment..."
if [ -d "$VENV" ]; then
  "$VENV/bin/python3" -c "import pymssql, openpyxl" 2>/dev/null \
    || { echo "       Rebuilding venv..."; rm -rf "$VENV"; }
fi

if [ ! -d "$VENV" ]; then
  python3 -m venv "$VENV" || fail "python3 -m venv failed"
  source "$VENV/bin/activate"
  pip install --upgrade pip setuptools wheel --quiet 2>/dev/null
  pip install pymssql --prefer-binary --quiet 2>/dev/null || fail "pymssql install failed"
  pip install openpyxl --quiet 2>/dev/null               || fail "openpyxl install failed"
fi
ok "Python environment ready"

# ── STEP 3: SQL credentials ─────────────────────────────────
step 3 "SQL credentials..."
export SQL_SERVER="173.249.59.109"
export SQL_PORT="1433"
export SQL_DATABASE="mwananchidy365"
export SQL_USER="monday"

[ -f "$CREDS" ] && source "$CREDS" 2>/dev/null

if [ -z "$SQL_PASSWORD" ]; then
  read -s -p "       Enter SQL password: " SQL_PASSWORD
  echo ""
  echo "SQL_PASSWORD='$SQL_PASSWORD'" > "$CREDS"
  chmod 600 "$CREDS"
  ok "Password saved to $CREDS"
else
  ok "Using saved password"
fi
export SQL_PASSWORD

# ── STEP 4: Test connection ─────────────────────────────────
step 4 "Testing SQL Server connection..."
"$VENV/bin/python3" - <<PYEOF
import os, sys, pymssql
try:
    conn = pymssql.connect(
        server=os.environ['SQL_SERVER'],
        port=int(os.environ['SQL_PORT']),
        user=os.environ['SQL_USER'],
        password=os.environ['SQL_PASSWORD'],
        database=os.environ['SQL_DATABASE'],
        login_timeout=10, as_dict=True
    )
    conn.close()
    print("       Connected")
    sys.exit(0)
except Exception as e:
    print(f"       FAIL: {e}")
    sys.exit(1)
PYEOF
[ $? -eq 0 ] || fail "Cannot connect to SQL Server. Check password and network."

# ── STEP 5: Create wrapper script ───────────────────────────
step 5 "Creating refresh wrapper script..."
cat > "$WRAPPER" <<WRAPPER
#!/bin/bash
# Auto-generated by MCL_AutoRefresh_Install.command — do not edit manually
source "$CREDS" 2>/dev/null
export SQL_SERVER="173.249.59.109"
export SQL_PORT="1433"
export SQL_DATABASE="mwananchidy365"
export SQL_USER="monday"
export SQL_PASSWORD

REPO="$REPO_DIR"
VENV_PY="$VENV/bin/python3"
SCRIPT="$SCRIPT"
TODAY=\$(date +"%Y-%m-%d")

# Run live refresh (fixed filename — Excel keeps this open)
"\$VENV_PY" "\$SCRIPT" "\$TODAY" "ALL" "MCL_Portfolio_LIVE.xlsx" >> "$LOG" 2>&1
WRAPPER

chmod +x "$WRAPPER"
ok "Wrapper created: $WRAPPER"

# ── STEP 6: Create daily snapshot script ────────────────────
DAILY_WRAPPER="$REPO_DIR/mcl_daily_snapshot.sh"
cat > "$DAILY_WRAPPER" <<SNAP
#!/bin/bash
# Auto-generated by MCL_AutoRefresh_Install.command — do not edit manually
source "$CREDS" 2>/dev/null
export SQL_SERVER="173.249.59.109"
export SQL_PORT="1433"
export SQL_DATABASE="mwananchidy365"
export SQL_USER="monday"
export SQL_PASSWORD

REPO="$REPO_DIR"
VENV_PY="$VENV/bin/python3"
SCRIPT="$SCRIPT"
TODAY=\$(date +"%Y-%m-%d")

# Run daily snapshot (dated filename)
"\$VENV_PY" "\$SCRIPT" "\$TODAY" "ALL" >> "$LOG" 2>&1

# macOS notification
osascript -e "display notification \"Daily snapshot ready: MCL_Portfolio_\${TODAY}.xlsx\" with title \"Mwananchi Credit\" sound name \"Glass\""
SNAP

chmod +x "$DAILY_WRAPPER"
ok "Daily snapshot wrapper created"

# ── STEP 7: Install LaunchAgent — 5-minute refresh ──────────
step 6 "Installing 5-minute refresh agent..."
mkdir -p "$AGENTS_DIR"

# Unload if already installed
launchctl unload "$LIVE_PLIST" 2>/dev/null

cat > "$LIVE_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.mcl.portfolio.refresh</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$WRAPPER</string>
    </array>
    <key>StartInterval</key>
    <integer>300</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$LOG</string>
    <key>StandardErrorPath</key>
    <string>$LOG</string>
</dict>
</plist>
PLIST

launchctl load "$LIVE_PLIST" && ok "5-minute refresh agent loaded" \
  || fail "Could not load LaunchAgent. Check $LIVE_PLIST"

# ── STEP 8: Install LaunchAgent — daily 5pm snapshot ────────
step 7 "Installing daily 5:00 PM snapshot agent..."

# Ask for preferred hour
echo ""
echo "       What time should the daily snapshot run?"
echo "       Enter hour in 24h format (e.g. 17 = 5pm, 8 = 8am)"
echo "       Press Enter for default: 17 (5:00 PM)"
echo ""
read -p "       Hour [17]: " INPUT_HOUR
SNAPSHOT_HOUR="${INPUT_HOUR:-17}"
if ! [[ "$SNAPSHOT_HOUR" =~ ^[0-9]+$ ]] || [ "$SNAPSHOT_HOUR" -gt 23 ]; then
  SNAPSHOT_HOUR=17
fi
ok "Daily snapshot will run at ${SNAPSHOT_HOUR}:00"

launchctl unload "$DAILY_PLIST" 2>/dev/null

cat > "$DAILY_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.mcl.portfolio.daily</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$DAILY_WRAPPER</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>$SNAPSHOT_HOUR</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$LOG</string>
    <key>StandardErrorPath</key>
    <string>$LOG</string>
</dict>
</plist>
PLIST

launchctl load "$DAILY_PLIST" && ok "Daily snapshot agent loaded (runs at ${SNAPSHOT_HOUR}:00)" \
  || fail "Could not load daily agent."

# ── STEP 9: First run ────────────────────────────────────────
step 8 "Running first refresh now..."
bash "$WRAPPER"

LIVE_FILE="$REPO_DIR/MCL_Portfolio_LIVE.xlsx"
if [ -f "$LIVE_FILE" ]; then
  open "$LIVE_FILE"
  ok "Excel opened: $LIVE_FILE"
else
  echo "       Refresh is running in background — check $LOG for progress"
fi

echo ""
echo "========================================================"
echo "  DONE — Auto-refresh is now active"
echo ""
echo "  5-minute live file:   MCL_Portfolio_LIVE.xlsx"
echo "  Daily snapshot time:  ${SNAPSHOT_HOUR}:00 (MCL_Portfolio_YYYY-MM-DD.xlsx)"
echo ""
echo "  Keep MCL_Portfolio_LIVE.xlsx open in Excel."
echo "  It will update automatically every 5 minutes."
echo ""
echo "  To stop auto-refresh:"
echo "    launchctl unload ~/Library/LaunchAgents/com.mcl.portfolio.refresh.plist"
echo "    launchctl unload ~/Library/LaunchAgents/com.mcl.portfolio.daily.plist"
echo ""
echo "  Refresh log:  ~/.mcl_refresh.log"
echo "========================================================"
echo ""
read -p "  Press Enter to close..."
